/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package black_Candy_jjt;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMT = 1;
  public int JJTASSIGMNET = 2;
  public int JJTIDEN = 3;
  public int JJTVAR = 4;
  public int JJTINDEXEND = 5;
  public int JJTARRRAYELEMENTS = 6;
  public int JJTARRAY = 7;
  public int JJTDATA_TYPE = 8;
  public int JJTNUMBERS = 9;
  public int JJTARTHIMETIC = 10;
  public int JJTCOMPARISONS = 11;
  public int JJTLOGICALOPERATOR = 12;
  public int JJTRELATIONALOPERATOR = 13;
  public int JJTCONDITION = 14;
  public int JJTCON = 15;


  public String[] jjtNodeName = {
    "start",
    "STMT",
    "ASSIGMNET",
    "IDEN",
    "VAR",
    "INDEXend",
    "ArrrayElements",
    "ARRAY",
    "DATA_TYPE",
    "Numbers",
    "ARTHIMETIC",
    "Comparisons",
    "LogicalOperator",
    "RelationalOperator",
    "CONDITION",
    "CON",
  };
}
/* JavaCC - OriginalChecksum=5cdf6b3fc60f49e49a7e79aacb034f0c (do not edit this line) */
